# Generated by Django 2.1.1 on 2018-09-22 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionTable',
            fields=[
                ('qid', models.CharField(max_length=25, primary_key=True, serialize=False, verbose_name='Question ID')),
                ('qtext', models.CharField(max_length=125, verbose_name='Question Text')),
                ('opt1', models.CharField(max_length=50, verbose_name='Option 1')),
                ('opt2', models.CharField(max_length=50, verbose_name='Option 2')),
                ('opt3', models.CharField(max_length=50, verbose_name='Option 3')),
                ('opt4', models.CharField(max_length=50, verbose_name='Option 4')),
                ('ans', models.CharField(max_length=25, verbose_name='Correct Answer')),
            ],
            options={
                'verbose_name_plural': 'QUESTION TABLE',
            },
        ),
        migrations.CreateModel(
            name='QuizTable',
            fields=[
                ('qno', models.IntegerField(primary_key=True, serialize=False, verbose_name='QUIZ NUMBER')),
                ('qdesc', models.CharField(max_length=50, verbose_name='QUIZ Description')),
            ],
            options={
                'verbose_name_plural': 'QUIZ TABLE',
            },
        ),
        migrations.AddField(
            model_name='questiontable',
            name='qno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.QuizTable', verbose_name='QUIZ NUMBER'),
        ),
    ]
